//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_House_demands_
    {
        public int Id { get; set; }
        public Nullable<int> Id_Demands { get; set; }
        public string Address_City { get; set; }
        public string Address_Street { get; set; }
        public Nullable<int> Address_House { get; set; }
        public Nullable<int> Address_Number { get; set; }
        public Nullable<int> MinFloors { get; set; }
        public Nullable<int> MaxFloors { get; set; }
        public Nullable<int> MinArea { get; set; }
        public Nullable<int> MaxArea { get; set; }
        public Nullable<int> MinRooms { get; set; }
        public Nullable<int> MaxRooms { get; set; }
    
        public virtual Demand Demand { get; set; }
    }
}
